#!/bin/bash

# Print the strings on separate lines
echo "one"
echo "two"
echo "three"
echo "four"
echo "five"

# Create a text file with the current date as the file name
infinity=$(date +"%Y-%m-%d-file.txt")
echo "one" > "$filename"
echo "two" >> "$filename"
echo "three" >> "$filename"
echo "four" >> "$filename"
echo "five" >> "$filename"

